name: selenium Test workflow

on:
  push:
    branches: main
  pull_request:
    branches: main


jobs:
  build:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v2
      - uses: nakajiss/DockerSeleniumAction@main
