name: selenium Test workflow


      
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: <Any name> 
    steps:
    - uses: actions/checkout@v2
    - name: <e.g. Zalenium >
      uses: ajinx/zalenium@1.1
    - name: Run test
      env:
        SELENIUM_HUB_HOST: 'localhost'
      run: mvn test
